### ISSUE TITLE
请问下菜单无法触发出来是怎么回事呢？

### ISSUE THREAD

**Issue by leesama** [izhaoo/hexo-theme-zhaoo#10]

**Comment by leesama** [comment]
https://leesher.gitee.io/

**Comment by izhaoo** [comment]
这个设计的时候是考虑，当页面超过一页的时候才会显示【菜单】，为了首屏美观。

当然了，我已经考虑到了，可以在 `_config.yml` 中开启 `alwaysShow` 配置，如下：

```yml
# Fab (FloatActionButton)
fab:
  enable: true
  alwaysShow: true  #总是显示
```

或者加油写文章，内容多了，超过一页，下滑后也会显示的~
