### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by xiao-js** [izhaoo/hexo-theme-zhaoo#12]
![image](https://user-images.githubusercontent.com/29617979/88476276-bdbcbc80-cf69-11ea-879d-9bcede7c45e3.png)

**Comment by izhaoo** [comment]
oh，不好意思，昨天开发了点新功能，配置文件忘更新了。

你可以先在 `_config.yml` 中添加以下配置项，就可以开起来了：

```yml
# Copyright
post_copyright:
  enable: true

# Thief（copy article with one click）
thief:
  enable: true
  type: html  #markdown
```

我开发完后再统一更新……
