### ISSUE TITLE
代码高亮无作用

### ISSUE THREAD

**Issue by ShiqiP** [izhaoo/hexo-theme-zhaoo#123]
如题，配置如下，但是没有代码高亮
```yml
# themes 的 _config.yml配置
highlight:
  enable: true
  style: # https://highlightjs.org/static/demo/
    light: Solarized Dark
    dark: Solarized Dark

# 根目录的 _config.yml配置
highlight:
  enable: true  #启用代码高亮效果
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
```
![image](https://github.com/zhaoo/hexo-theme-zhaoo/assets/49100446/d83b68a4-04bd-4550-9300-e79306edd826)

**Comment by YuWeiKuo** [comment]
你在md文档里的代码是这样吗？

```javascript
你的代码
```
如果不是确实不会高亮

**Comment by YuWeiKuo** [comment]
你在markdown 文档里的代码是这样吗？有加 ```吗？
<img width="850" alt="截圖 2023-12-28 晚上7 51 40" src="https://github.com/zhaoo/hexo-theme-zhaoo/assets/45961933/7fe10248-e9e1-4c58-9598-60ed758d793b">

如果不是这样确实不会高亮

**Comment by ShiqiP** [comment]
已经解决了，是我这个<code>hljs</code>配置没开
```yml
# 根目录的 _config.yml配置
highlight:
  enable: true  #启用代码高亮效果
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false // 应该改ture
```
