### ISSUE TITLE
how to config loading image?

### ISSUE THREAD

**Issue by ClearLoving** [izhaoo/hexo-theme-zhaoo#21]
My root URL is /xxx, I have set the lazyLoad like this:

```yaml
 lazyload:
       enable: true
       onlyPost: false
       loadingImage: /xxxx/images/theme/loading.gif
```
but in the style.css file:

```css
.lazyload {
    background: url("/xxxx/images/theme/loading.gif") center center no-repeat;
}
.loading {
    position: fixed;
    width: 100%;
    height: 100%;
    top: 0px;
    background: url("/images/theme/loading.gif") center center no-repeat rgb(255, 255, 255);
    z-index: 2019;
    overflow: hidden;
}
```
the `.loading` class lacks of prefix `/xxxx`, how to set it ?

**Comment by izhaoo** [comment]
已修复，全局 `loading` 和 懒加载的 `loading` 分开设置，如下：

```yml
# Loading
loading: /images/theme/loading.gif

# Lazyload
lazyload:
  enable: true
  onlyPost: false
  loading: /images/theme/loading.gif
```
