### ISSUE TITLE
希望增加文章头图随机选择功能，以及关于图片宽高比压缩问题

### ISSUE THREAD

**Issue by HandwerSTD** [izhaoo/hexo-theme-zhaoo#23]
如题，用了好几年的博客，一共一百来篇文章，一个一个加头图说实话不是很简单。。
希望加入一个随机的头图选择功能，头图列表建议直接用 galleries.json 就可以，或者新开一个 json 存

另外就是首页图片和头图好像会有宽高比压缩现象，希望能自适应一下，或者在文档里写一个推荐的宽高比
![image](https://user-images.githubusercontent.com/37949764/96201145-5f164600-0f8e-11eb-9072-442c0e065cf5.png)

![image](https://user-images.githubusercontent.com/37949764/96201057-1b234100-0f8e-11eb-935a-a26ea6ad0fdc.png)

左为图片原图，右为首页图显示效果，虽然这张图影响不大，但是其他图可能就有点问题，还是希望调整一下。

最后提前感谢开发者

**Comment by izhaoo** [comment]
安排，最佳尺寸是：1920x1080

**Comment by HandwerSTD** [comment]
我想了一下，可能用独立的 json 文件比较好，毕竟 galleries.json 里面的照片有时候可能尺寸不合适，还是单独裁剪一下比较好

**Comment by izhaoo** [comment]
done

**Comment by izhaoo** [comment]
在 `/hexo/themes/zhaoo/_config.yml` 下开启：

```yml
# Post image
post_image:
  random: true # need to turn on galleries
  default: /images/theme/post-image.jpg
```

还是决定获取 `galleries.json` 里的图片，后期会对尺寸做一个适配。
