### ISSUE TITLE
希望增加数学公式支持

### ISSUE THREAD

**Issue by HandwerSTD** [izhaoo/hexo-theme-zhaoo#24]
如题，这个功能还是比较重要的，KaTeX 和 MathJax 都可以，mhchem 支持也希望有
![image](https://user-images.githubusercontent.com/37949764/96201819-29725c80-0f90-11eb-9d47-6dacba8fe046.png)

**Comment by izhaoo** [comment]
安排

**Comment by izhaoo** [comment]
### MathJax

1. 安装插件支持

```bash
npm install hexo-filter-mathjax-ssr --save
```

2. 开启插件

在配置文件 `/hexo/_config.yml` 下新增：

```yml
mathjax:
  inlineQuote: ['\(', '\)']
  blockQuote: ['\[', '\]']
```
