### ISSUE TITLE
部署问题:hexo g之后index.html没有样式

### ISSUE THREAD

**Issue by chaserzz** [izhaoo/hexo-theme-zhaoo#27]
在本地浏览器上跑动是没有问题的,可是一旦建立了index.html之后，打开没有样式并且点击出现无法找到文件

**Comment by chaserzz** [comment]
![image](https://user-images.githubusercontent.com/51116866/96328610-9f9dbe80-1077-11eb-908b-eef1a7e171df.png)
zh
这是打开之后的报错

**Comment by izhaoo** [comment]
应该是博客路径的问题，我现在在山上，晚上回复你。


 
---原始邮件---
发件人: "chaserzz"<notifications@github.com&gt;
发送时间: 2020年10月17日 12:53:02
收件人: "izhaoo/hexo-theme-zhaoo"<hexo-theme-zhaoo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [izhaoo/hexo-theme-zhaoo] 部署问题:hexo g之后index.html没有样式 (#27)




 

 zh
 这是打开之后的报错

**Comment by izhaoo** [comment]
可以检查一下 `_config.yml` 文件下的以下配置：

```yml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.izhaoo.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
```

`url` 和 `root` 我这边是这样配置的。
